import api from '../../api';

/**
 * Groq Provider
 * 
 * Why does this exist?
 * It implements the Provider Pattern. It acts as the bridge between our React frontend
 * and our secure Node.js backend for AI features. 
 * We migrated to Groq for faster inference using the LLaMA models.
 * 
 * Why do we use the backend instead of calling Groq directly?
 * Security! If we call Groq directly from React, the API key would be visible in the browser network tab.
 * By calling our own backend, the API key stays securely on our server.
 * 
 * Input: user's prompt, conversation history, and system instructions.
 * Output: The final text response generated by Groq (via our backend).
 */

class GroqProvider {
  /**
   * Generates a response by securely calling our backend API
   * 
   * @param {string} prompt - The user's new message
   * @param {Array} history - The history of the conversation to provide context
   * @param {string} systemPrompt - The rules governing the AI's behavior
   * @returns {string} The text response
   */
  async generate(prompt, history, systemPrompt) {
    try {
      // We use our pre-configured Axios instance (api) which automatically
      // attaches the user's JWT token for authentication.
      // This sends the data to our Node.js backend controller.
      const response = await api.post('/ai/chat', {
        prompt,
        history,
        systemPrompt
      });

      // Our backend returns the generated text in the `response` property
      return response.data.response;
    } catch (error) {
      // Centralized error handling
      console.error("GroqProvider Error:", error);
      
      // If the backend returned a specific rate limit error, throw it so the UI can handle it gracefully.
      if (error.response && error.response.status === 429) {
          throw new Error("Rate limit exceeded. Please try again later.");
      }

      // Propagate user-friendly errors sent by the backend if they exist
      if (error.response && error.response.data && error.response.data.message) {
        throw new Error(error.response.data.message);
      }

      throw new Error("Failed to generate AI response.");
    }
  }
}

export default GroqProvider;
