import api from '../../api';

/**
 * Gemini Provider
 * 
 * Why does this exist?
 * It implements the Provider Pattern. It acts as the bridge between our React frontend
 * and our secure Node.js backend for AI features.
 * 
 * Why do we use the backend instead of calling Gemini directly?
 * Security! If we call Gemini directly from React, the API key would be visible in the browser network tab.
 * By calling our own backend, the API key stays securely on our server.
 * 
 * Input: user's prompt, conversation history, and system instructions.
 * Output: The final text response generated by Gemini (via our backend).
 */

class GeminiProvider {
  /**
   * Generates a response by securely calling our backend API
   * 
   * @param {string} prompt - The user's new message
   * @param {Array} history - The history of the conversation to provide context
   * @param {string} systemPrompt - The rules governing the AI's behavior
   * @returns {string} The text response
   */
  async generate(prompt, history, systemPrompt) {
    try {
      // We use our pre-configured Axios instance (api) which automatically
      // attaches the user's JWT token for authentication.
      const response = await api.post('/ai/chat', {
        prompt,
        history,
        systemPrompt
      });

      // Our backend returns the generated text in the `response` property
      return response.data.response;
    } catch (error) {
      // Centralized error handling
      console.error("GeminiProvider Error:", error);
      
      // If the backend returned a specific rate limit error, throw it so the UI can handle it gracefully.
      if (error.response && error.response.status === 429) {
          throw new Error("Rate limit exceeded");
      }

      throw new Error("Failed to generate AI response.");
    }
  }
}

export default GeminiProvider;
